# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Adaboost_UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1014, 734)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(12, 20, 981, 701))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.headingLabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.headingLabel_2.setFont(font)
        self.headingLabel_2.setObjectName("headingLabel_2")
        self.verticalLayout_3.addWidget(self.headingLabel_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.dataPath_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.dataPath_2.setFont(font)
        self.dataPath_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dataPath_2.setObjectName("dataPath_2")
        self.horizontalLayout_3.addWidget(self.dataPath_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.choseDataBtn = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.choseDataBtn.setObjectName("choseDataBtn")
        self.horizontalLayout_2.addWidget(self.choseDataBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.startTrainBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startTrainBtn.setObjectName("startTrainBtn")
        self.verticalLayout_3.addWidget(self.startTrainBtn)
        self.line_5 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        spacerItem = QtWidgets.QSpacerItem(515, 485, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(22)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.profitCol = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.profitCol.setFont(font)
        self.profitCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.profitCol.setObjectName("profitCol")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.profitCol)
        self.profitOut = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.profitOut.setFont(font)
        self.profitOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.profitOut.setObjectName("profitOut")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.profitOut)
        self.winrateCol_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.winrateCol_3.setFont(font)
        self.winrateCol_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.winrateCol_3.setObjectName("winrateCol_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.winrateCol_3)
        self.winRateOut = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.winRateOut.setFont(font)
        self.winRateOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.winRateOut.setObjectName("winRateOut")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.winRateOut)
        self.winLossCol = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.winLossCol.setFont(font)
        self.winLossCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.winLossCol.setObjectName("winLossCol")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.winLossCol)
        self.winLossOut = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.winLossOut.setFont(font)
        self.winLossOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.winLossOut.setObjectName("winLossOut")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.winLossOut)
        self.profitFactorCol = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.profitFactorCol.setFont(font)
        self.profitFactorCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.profitFactorCol.setObjectName("profitFactorCol")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.profitFactorCol)
        self.profitFactorOut = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.profitFactorOut.setFont(font)
        self.profitFactorOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.profitFactorOut.setObjectName("profitFactorOut")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.profitFactorOut)
        self.mddCol = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.mddCol.setFont(font)
        self.mddCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mddCol.setObjectName("mddCol")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.mddCol)
        self.mddOut = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.mddOut.setFont(font)
        self.mddOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mddOut.setObjectName("mddOut")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.mddOut)
        self.sharpeCol = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.sharpeCol.setFont(font)
        self.sharpeCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sharpeCol.setObjectName("sharpeCol")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.sharpeCol)
        self.tradeCuntOut = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.tradeCuntOut.setFont(font)
        self.tradeCuntOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tradeCuntOut.setObjectName("tradeCuntOut")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.tradeCuntOut)
        self.costCol = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.costCol.setFont(font)
        self.costCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.costCol.setObjectName("costCol")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.costCol)
        self.costOut = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.costOut.setFont(font)
        self.costOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.costOut.setObjectName("costOut")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.costOut)
        self.verticalLayout_7.addLayout(self.formLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 188, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.headingLabel_2.setText(_translate("Form", "ADABOOST"))
        self.label_15.setText(_translate("Form", "檔案:"))
        self.dataPath_2.setText(_translate("Form", "--"))
        self.choseDataBtn.setText(_translate("Form", "..."))
        self.startTrainBtn.setText(_translate("Form", "開始訓練"))
        self.label_6.setText(_translate("Form", "績效"))
        self.profitCol.setText(_translate("Form", "淨利:"))
        self.profitOut.setText(_translate("Form", "─"))
        self.winrateCol_3.setText(_translate("Form", "勝率:"))
        self.winRateOut.setText(_translate("Form", "─"))
        self.winLossCol.setText(_translate("Form", "賺賠比:"))
        self.winLossOut.setText(_translate("Form", "─"))
        self.profitFactorCol.setText(_translate("Form", "獲利因子:"))
        self.profitFactorOut.setText(_translate("Form", "─"))
        self.mddCol.setText(_translate("Form", "最大策略虧損:"))
        self.mddOut.setText(_translate("Form", "─"))
        self.sharpeCol.setText(_translate("Form", "總交易次數:"))
        self.tradeCuntOut.setText(_translate("Form", "─"))
        self.costCol.setText(_translate("Form", "交易成本:"))
        self.costOut.setText(_translate("Form", "─"))

