# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'New_UI_for_edit.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 806)
        MainWindow.setStyleSheet("border-color: rgb(242, 242, 242);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 462, 733))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title1.setObjectName("title1")
        self.gridLayout_2.addWidget(self.title1, 0, 0, 1, 1)
        self.link1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.link1.setObjectName("link1")
        self.gridLayout_2.addWidget(self.link1, 0, 1, 1, 1)
        self.title2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title2.setObjectName("title2")
        self.gridLayout_2.addWidget(self.title2, 1, 0, 1, 1)
        self.link2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.link2.setObjectName("link2")
        self.gridLayout_2.addWidget(self.link2, 1, 1, 1, 1)
        self.title3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title3.setObjectName("title3")
        self.gridLayout_2.addWidget(self.title3, 2, 0, 1, 1)
        self.link3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.link3.setObjectName("link3")
        self.gridLayout_2.addWidget(self.link3, 2, 1, 1, 1)
        self.title4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title4.setObjectName("title4")
        self.gridLayout_2.addWidget(self.title4, 3, 0, 1, 1)
        self.link4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.link4.setObjectName("link4")
        self.gridLayout_2.addWidget(self.link4, 3, 1, 1, 1)
        self.title5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title5.setObjectName("title5")
        self.gridLayout_2.addWidget(self.title5, 4, 0, 1, 1)
        self.link5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.link5.setObjectName("link5")
        self.gridLayout_2.addWidget(self.link5, 4, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3.addWidget(self.frame, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 24))
        self.menubar.setDefaultUp(True)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setSizeIncrement(QtCore.QSize(0, 0))
        self.menu.setObjectName("menu")
        self.menuMachineLearning = QtWidgets.QMenu(self.menu)
        self.menuMachineLearning.setObjectName("menuMachineLearning")
        self.menuStrategy = QtWidgets.QMenu(self.menu)
        self.menuStrategy.setObjectName("menuStrategy")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.menu_3.setObjectName("menu_3")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTurtle_2 = QtWidgets.QAction(MainWindow)
        self.actionTurtle_2.setObjectName("actionTurtle_2")
        self.actionRangeBreak_2 = QtWidgets.QAction(MainWindow)
        self.actionRangeBreak_2.setObjectName("actionRangeBreak_2")
        self.actionRF = QtWidgets.QAction(MainWindow)
        self.actionRF.setObjectName("actionRF")
        self.actionDT = QtWidgets.QAction(MainWindow)
        self.actionDT.setObjectName("actionDT")
        self.actionLSTM = QtWidgets.QAction(MainWindow)
        self.actionLSTM.setObjectName("actionLSTM")
        self.actionMLP = QtWidgets.QAction(MainWindow)
        self.actionMLP.setObjectName("actionMLP")
        self.actionTurtle = QtWidgets.QAction(MainWindow)
        self.actionTurtle.setObjectName("actionTurtle")
        self.actionRangeBreak = QtWidgets.QAction(MainWindow)
        self.actionRangeBreak.setObjectName("actionRangeBreak")
        self.actionAverage = QtWidgets.QAction(MainWindow)
        self.actionAverage.setObjectName("actionAverage")
        self.actionRF_2 = QtWidgets.QAction(MainWindow)
        self.actionRF_2.setObjectName("actionRF_2")
        self.actionDT_2 = QtWidgets.QAction(MainWindow)
        self.actionDT_2.setObjectName("actionDT_2")
        self.actionLSTM_2 = QtWidgets.QAction(MainWindow)
        self.actionLSTM_2.setObjectName("actionLSTM_2")
        self.actionMLP_2 = QtWidgets.QAction(MainWindow)
        self.actionMLP_2.setObjectName("actionMLP_2")
        self.actionAverage_2 = QtWidgets.QAction(MainWindow)
        self.actionAverage_2.setObjectName("actionAverage_2")
        self.actionMulticharts = QtWidgets.QAction(MainWindow)
        self.actionMulticharts.setObjectName("actionMulticharts")
        self.actionCCI = QtWidgets.QAction(MainWindow)
        self.actionCCI.setObjectName("actionCCI")
        self.actionCCI_2 = QtWidgets.QAction(MainWindow)
        self.actionCCI_2.setObjectName("actionCCI_2")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAboutMC = QtWidgets.QAction(MainWindow)
        self.actionAboutMC.setObjectName("actionAboutMC")
        self.menuMachineLearning.addAction(self.actionRF)
        self.menuMachineLearning.addAction(self.actionDT)
        self.menuMachineLearning.addAction(self.actionLSTM)
        self.menuMachineLearning.addAction(self.actionMLP)
        self.menuStrategy.addAction(self.actionTurtle)
        self.menuStrategy.addAction(self.actionRangeBreak)
        self.menuStrategy.addAction(self.actionAverage)
        self.menuStrategy.addAction(self.actionCCI)
        self.menu.addAction(self.menuMachineLearning.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.menuStrategy.menuAction())
        self.menu_2.addAction(self.actionTurtle_2)
        self.menu_2.addAction(self.actionRangeBreak_2)
        self.menu_2.addAction(self.actionAverage_2)
        self.menu_2.addAction(self.actionCCI_2)
        self.menu_3.addAction(self.actionRF_2)
        self.menu_3.addAction(self.actionDT_2)
        self.menu_3.addAction(self.actionLSTM_2)
        self.menu_3.addAction(self.actionMLP_2)
        self.menuOpen.addAction(self.actionMulticharts)
        self.menu_4.addAction(self.actionAbout)
        self.menu_4.addAction(self.actionAboutMC)
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuOpen.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title1.setText(_translate("MainWindow", "TextLabel"))
        self.link1.setText(_translate("MainWindow", "TextLabel"))
        self.title2.setText(_translate("MainWindow", "TextLabel"))
        self.link2.setText(_translate("MainWindow", "TextLabel"))
        self.title3.setText(_translate("MainWindow", "TextLabel"))
        self.link3.setText(_translate("MainWindow", "TextLabel"))
        self.title4.setText(_translate("MainWindow", "TextLabel"))
        self.link4.setText(_translate("MainWindow", "TextLabel"))
        self.title5.setText(_translate("MainWindow", "TextLabel"))
        self.link5.setText(_translate("MainWindow", "TextLabel"))
        self.menu.setTitle(_translate("MainWindow", "策略管理"))
        self.menuMachineLearning.setTitle(_translate("MainWindow", "機器學習"))
        self.menuStrategy.setTitle(_translate("MainWindow", "程式交易"))
        self.menu_2.setTitle(_translate("MainWindow", "交易策略"))
        self.menu_3.setTitle(_translate("MainWindow", "智能交易"))
        self.menuOpen.setTitle(_translate("MainWindow", "開啟"))
        self.menu_4.setTitle(_translate("MainWindow", "設置"))
        self.actionTurtle_2.setText(_translate("MainWindow", "Turtle"))
        self.actionRangeBreak_2.setText(_translate("MainWindow", "RangeBreak"))
        self.actionRF.setText(_translate("MainWindow", "RF"))
        self.actionDT.setText(_translate("MainWindow", "DT"))
        self.actionLSTM.setText(_translate("MainWindow", "LSTM"))
        self.actionMLP.setText(_translate("MainWindow", "MLP"))
        self.actionTurtle.setText(_translate("MainWindow", "Turtle"))
        self.actionRangeBreak.setText(_translate("MainWindow", "RangeBreak"))
        self.actionAverage.setText(_translate("MainWindow", "MoveAverage"))
        self.actionRF_2.setText(_translate("MainWindow", "RF"))
        self.actionDT_2.setText(_translate("MainWindow", "DT"))
        self.actionLSTM_2.setText(_translate("MainWindow", "LSTM"))
        self.actionMLP_2.setText(_translate("MainWindow", "MLP"))
        self.actionAverage_2.setText(_translate("MainWindow", "MoveAverage"))
        self.actionMulticharts.setText(_translate("MainWindow", "Multicharts"))
        self.actionCCI.setText(_translate("MainWindow", "CCI"))
        self.actionCCI_2.setText(_translate("MainWindow", "CCI"))
        self.actionAbout.setText(_translate("MainWindow", "關於我們"))
        self.actionAboutMC.setText(_translate("MainWindow", "關於Multicharts"))