# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'New_UI_for_edit.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 806)
        MainWindow.setStyleSheet("border-color: rgb(242, 242, 242);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 462, 733))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title1.setObjectName("title1")
        self.gridLayout_2.addWidget(self.title1, 0, 0, 1, 1)
        self.link1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.link1.setObjectName("link1")
        self.gridLayout_2.addWidget(self.link1, 0, 1, 1, 1)
        self.title2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title2.setObjectName("title2")
        self.gridLayout_2.addWidget(self.title2, 1, 0, 1, 1)
        self.link2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.link2.setObjectName("link2")
        self.gridLayout_2.addWidget(self.link2, 1, 1, 1, 1)
        self.title3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title3.setObjectName("title3")
        self.gridLayout_2.addWidget(self.title3, 2, 0, 1, 1)
        self.link3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.link3.setObjectName("link3")
        self.gridLayout_2.addWidget(self.link3, 2, 1, 1, 1)
        self.title4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title4.setObjectName("title4")
        self.gridLayout_2.addWidget(self.title4, 3, 0, 1, 1)
        self.link4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.link4.setObjectName("link4")
        self.gridLayout_2.addWidget(self.link4, 3, 1, 1, 1)
        self.title5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title5.setObjectName("title5")
        self.gridLayout_2.addWidget(self.title5, 4, 0, 1, 1)
        self.link5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.link5.setObjectName("link5")
        self.gridLayout_2.addWidget(self.link5, 4, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3.addWidget(self.frame, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 24))
        self.menubar.setDefaultUp(True)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menu_Strategy = QtWidgets.QMenu(self.menubar)
        self.menu_Strategy.setSizeIncrement(QtCore.QSize(0, 0))
        self.menu_Strategy.setObjectName("menu_Strategy")
        self.menuTurtle = QtWidgets.QMenu(self.menu_Strategy)
        self.menuTurtle.setObjectName("menuTurtle")
        self.menuMoveAverage = QtWidgets.QMenu(self.menu_Strategy)
        self.menuMoveAverage.setObjectName("menuMoveAverage")
        self.menuRangeBreak = QtWidgets.QMenu(self.menu_Strategy)
        self.menuRangeBreak.setObjectName("menuRangeBreak")
        self.menu_AI = QtWidgets.QMenu(self.menubar)
        self.menu_AI.setSizeIncrement(QtCore.QSize(0, 0))
        self.menu_AI.setObjectName("menu_AI")
        self.menuMachineTranning = QtWidgets.QMenu(self.menu_AI)
        self.menuMachineTranning.setObjectName("menuMachineTranning")
        self.menuDT = QtWidgets.QMenu(self.menu_AI)
        self.menuDT.setObjectName("menuDT")
        self.menuRF = QtWidgets.QMenu(self.menu_AI)
        self.menuRF.setObjectName("menuRF")
        self.menuLSTM = QtWidgets.QMenu(self.menu_AI)
        self.menuLSTM.setObjectName("menuLSTM")
        self.menuMLP = QtWidgets.QMenu(self.menu_AI)
        self.menuMLP.setObjectName("menuMLP")
        self.menuAdaboost = QtWidgets.QMenu(self.menu_AI)
        self.menuAdaboost.setObjectName("menuAdaboost")
        self.menu_Open = QtWidgets.QMenu(self.menubar)
        self.menu_Open.setObjectName("menu_Open")
        self.menu_About = QtWidgets.QMenu(self.menubar)
        self.menu_About.setObjectName("menu_About")
        self.menu_Webcrawler = QtWidgets.QMenu(self.menubar)
        self.menu_Webcrawler.setObjectName("menu_Webcrawler")
        self.menuinformation = QtWidgets.QMenu(self.menu_Webcrawler)
        self.menuinformation.setObjectName("menuinformation")
        self.menu_Reports = QtWidgets.QMenu(self.menubar)
        self.menu_Reports.setObjectName("menu_Reports")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTurtle30k = QtWidgets.QAction(MainWindow)
        self.actionTurtle30k.setObjectName("actionTurtle30k")
        self.actionTurtle60k = QtWidgets.QAction(MainWindow)
        self.actionTurtle60k.setObjectName("actionTurtle60k")
        self.actionMulticharts = QtWidgets.QAction(MainWindow)
        self.actionMulticharts.setObjectName("actionMulticharts")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAboutMC = QtWidgets.QAction(MainWindow)
        self.actionAboutMC.setObjectName("actionAboutMC")
        self.actionrecentInfo = QtWidgets.QAction(MainWindow)
        self.actionrecentInfo.setObjectName("actionrecentInfo")
        self.actionMA_Original = QtWidgets.QAction(MainWindow)
        self.actionMA_Original.setObjectName("actionMA_Original")
        self.actionGetData = QtWidgets.QAction(MainWindow)
        self.actionGetData.setObjectName("actionGetData")
        self.actionTranningMachine = QtWidgets.QAction(MainWindow)
        self.actionTranningMachine.setObjectName("actionTranningMachine")
        self.actionDT_Original = QtWidgets.QAction(MainWindow)
        self.actionDT_Original.setObjectName("actionDT_Original")
        self.actionDT_Kelly = QtWidgets.QAction(MainWindow)
        self.actionDT_Kelly.setObjectName("actionDT_Kelly")
        self.actionDT_FixedRatio = QtWidgets.QAction(MainWindow)
        self.actionDT_FixedRatio.setObjectName("actionDT_FixedRatio")
        self.actionDT_OptimalF = QtWidgets.QAction(MainWindow)
        self.actionDT_OptimalF.setObjectName("actionDT_OptimalF")
        self.actionDT_LarryWilliams = QtWidgets.QAction(MainWindow)
        self.actionDT_LarryWilliams.setObjectName("actionDT_LarryWilliams")
        self.actionDT_AntiMartingale = QtWidgets.QAction(MainWindow)
        self.actionDT_AntiMartingale.setObjectName("actionDT_AntiMartingale")
        self.actionLSTM_Original = QtWidgets.QAction(MainWindow)
        self.actionLSTM_Original.setObjectName("actionLSTM_Original")
        self.actionLSTM_Kelly = QtWidgets.QAction(MainWindow)
        self.actionLSTM_Kelly.setObjectName("actionLSTM_Kelly")
        self.actionLSTM_FixedRatio = QtWidgets.QAction(MainWindow)
        self.actionLSTM_FixedRatio.setObjectName("actionLSTM_FixedRatio")
        self.actionLSTM_OptimalF = QtWidgets.QAction(MainWindow)
        self.actionLSTM_OptimalF.setObjectName("actionLSTM_OptimalF")
        self.actionLSTM_LarryWilliams = QtWidgets.QAction(MainWindow)
        self.actionLSTM_LarryWilliams.setObjectName("actionLSTM_LarryWilliams")
        self.actionLSTM_AntiMartingale = QtWidgets.QAction(MainWindow)
        self.actionLSTM_AntiMartingale.setObjectName("actionLSTM_AntiMartingale")
        self.actionRF_Original = QtWidgets.QAction(MainWindow)
        self.actionRF_Original.setObjectName("actionRF_Original")
        self.actionRF_Kelly = QtWidgets.QAction(MainWindow)
        self.actionRF_Kelly.setObjectName("actionRF_Kelly")
        self.actionRF_FixedRatio = QtWidgets.QAction(MainWindow)
        self.actionRF_FixedRatio.setObjectName("actionRF_FixedRatio")
        self.actionRF_OptimalF = QtWidgets.QAction(MainWindow)
        self.actionRF_OptimalF.setObjectName("actionRF_OptimalF")
        self.actionRF_LarryWilliams = QtWidgets.QAction(MainWindow)
        self.actionRF_LarryWilliams.setObjectName("actionRF_LarryWilliams")
        self.actionRF_AntiMartingale = QtWidgets.QAction(MainWindow)
        self.actionRF_AntiMartingale.setObjectName("actionRF_AntiMartingale")
        self.actionMLP_Original = QtWidgets.QAction(MainWindow)
        self.actionMLP_Original.setObjectName("actionMLP_Original")
        self.actionMLP_Kelly = QtWidgets.QAction(MainWindow)
        self.actionMLP_Kelly.setObjectName("actionMLP_Kelly")
        self.actionMLP_FixedRatio = QtWidgets.QAction(MainWindow)
        self.actionMLP_FixedRatio.setObjectName("actionMLP_FixedRatio")
        self.actionMLP_OptimalF = QtWidgets.QAction(MainWindow)
        self.actionMLP_OptimalF.setObjectName("actionMLP_OptimalF")
        self.actionMLP_LarryWilliams = QtWidgets.QAction(MainWindow)
        self.actionMLP_LarryWilliams.setObjectName("actionMLP_LarryWilliams")
        self.actionMLP_AntiMartingale = QtWidgets.QAction(MainWindow)
        self.actionMLP_AntiMartingale.setObjectName("actionMLP_AntiMartingale")
        self.actionAdaboost_Original = QtWidgets.QAction(MainWindow)
        self.actionAdaboost_Original.setObjectName("actionAdaboost_Original")
        self.actionAdaboost_Kelly = QtWidgets.QAction(MainWindow)
        self.actionAdaboost_Kelly.setObjectName("actionAdaboost_Kelly")
        self.actionAdaboost_FixedRatio = QtWidgets.QAction(MainWindow)
        self.actionAdaboost_FixedRatio.setObjectName("actionAdaboost_FixedRatio")
        self.actionAdaboost_OptimalF = QtWidgets.QAction(MainWindow)
        self.actionAdaboost_OptimalF.setObjectName("actionAdaboost_OptimalF")
        self.actionAdaboost_LarryWilliams = QtWidgets.QAction(MainWindow)
        self.actionAdaboost_LarryWilliams.setObjectName("actionAdaboost_LarryWilliams")
        self.actionAdaboost_AntiMartingale = QtWidgets.QAction(MainWindow)
        self.actionAdaboost_AntiMartingale.setObjectName("actionAdaboost_AntiMartingale")
        self.actionRangeBreak_Original = QtWidgets.QAction(MainWindow)
        self.actionRangeBreak_Original.setObjectName("actionRangeBreak_Original")
        self.actionPowerLanguage_Editor = QtWidgets.QAction(MainWindow)
        self.actionPowerLanguage_Editor.setObjectName("actionPowerLanguage_Editor")
        self.menuTurtle.addAction(self.actionTurtle30k)
        self.menuTurtle.addAction(self.actionTurtle60k)
        self.menuMoveAverage.addAction(self.actionMA_Original)
        self.menuRangeBreak.addAction(self.actionRangeBreak_Original)
        self.menu_Strategy.addAction(self.menuTurtle.menuAction())
        self.menu_Strategy.addAction(self.menuMoveAverage.menuAction())
        self.menu_Strategy.addAction(self.menuRangeBreak.menuAction())
        self.menuMachineTranning.addAction(self.actionGetData)
        self.menuMachineTranning.addAction(self.actionTranningMachine)
        self.menuDT.addAction(self.actionDT_Original)
        self.menuDT.addAction(self.actionDT_Kelly)
        self.menuDT.addAction(self.actionDT_FixedRatio)
        self.menuDT.addAction(self.actionDT_OptimalF)
        self.menuDT.addAction(self.actionDT_LarryWilliams)
        self.menuDT.addAction(self.actionDT_AntiMartingale)
        self.menuRF.addAction(self.actionRF_Original)
        self.menuRF.addAction(self.actionRF_Kelly)
        self.menuRF.addAction(self.actionRF_FixedRatio)
        self.menuRF.addAction(self.actionRF_OptimalF)
        self.menuRF.addAction(self.actionRF_LarryWilliams)
        self.menuRF.addAction(self.actionRF_AntiMartingale)
        self.menuLSTM.addAction(self.actionLSTM_Original)
        self.menuLSTM.addAction(self.actionLSTM_Kelly)
        self.menuLSTM.addAction(self.actionLSTM_FixedRatio)
        self.menuLSTM.addAction(self.actionLSTM_OptimalF)
        self.menuLSTM.addAction(self.actionLSTM_LarryWilliams)
        self.menuLSTM.addAction(self.actionLSTM_AntiMartingale)
        self.menuMLP.addAction(self.actionMLP_Original)
        self.menuMLP.addAction(self.actionMLP_Kelly)
        self.menuMLP.addAction(self.actionMLP_FixedRatio)
        self.menuMLP.addAction(self.actionMLP_OptimalF)
        self.menuMLP.addAction(self.actionMLP_LarryWilliams)
        self.menuMLP.addAction(self.actionMLP_AntiMartingale)
        self.menuAdaboost.addAction(self.actionAdaboost_Original)
        self.menuAdaboost.addAction(self.actionAdaboost_Kelly)
        self.menuAdaboost.addAction(self.actionAdaboost_FixedRatio)
        self.menuAdaboost.addAction(self.actionAdaboost_OptimalF)
        self.menuAdaboost.addAction(self.actionAdaboost_LarryWilliams)
        self.menuAdaboost.addAction(self.actionAdaboost_AntiMartingale)
        self.menu_AI.addAction(self.menuMachineTranning.menuAction())
        self.menu_AI.addAction(self.menuDT.menuAction())
        self.menu_AI.addAction(self.menuRF.menuAction())
        self.menu_AI.addAction(self.menuLSTM.menuAction())
        self.menu_AI.addAction(self.menuMLP.menuAction())
        self.menu_AI.addAction(self.menuAdaboost.menuAction())
        self.menu_Open.addAction(self.actionMulticharts)
        self.menu_Open.addAction(self.actionPowerLanguage_Editor)
        self.menu_About.addAction(self.actionAbout)
        self.menu_About.addAction(self.actionAboutMC)
        self.menuinformation.addAction(self.actionrecentInfo)
        self.menu_Webcrawler.addAction(self.menuinformation.menuAction())
        self.menubar.addAction(self.menu_Strategy.menuAction())
        self.menubar.addAction(self.menu_AI.menuAction())
        self.menubar.addAction(self.menu_Webcrawler.menuAction())
        self.menubar.addAction(self.menu_Reports.menuAction())
        self.menubar.addAction(self.menu_Open.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title1.setText(_translate("MainWindow", "TextLabel"))
        self.link1.setText(_translate("MainWindow", "TextLabel"))
        self.title2.setText(_translate("MainWindow", "TextLabel"))
        self.link2.setText(_translate("MainWindow", "TextLabel"))
        self.title3.setText(_translate("MainWindow", "TextLabel"))
        self.link3.setText(_translate("MainWindow", "TextLabel"))
        self.title4.setText(_translate("MainWindow", "TextLabel"))
        self.link4.setText(_translate("MainWindow", "TextLabel"))
        self.title5.setText(_translate("MainWindow", "TextLabel"))
        self.link5.setText(_translate("MainWindow", "TextLabel"))
        self.menu_Strategy.setTitle(_translate("MainWindow", "交易策略"))
        self.menuTurtle.setTitle(_translate("MainWindow", "海龜"))
        self.menuMoveAverage.setTitle(_translate("MainWindow", "移動均線"))
        self.menuRangeBreak.setTitle(_translate("MainWindow", "區間突破"))
        self.menu_AI.setTitle(_translate("MainWindow", "智能交易"))
        self.menuMachineTranning.setTitle(_translate("MainWindow", "機器訓練"))
        self.menuDT.setTitle(_translate("MainWindow", "決策樹(DT)"))
        self.menuRF.setTitle(_translate("MainWindow", "隨機森林(RF)"))
        self.menuLSTM.setTitle(_translate("MainWindow", "長短期記憶(LSTM)"))
        self.menuMLP.setTitle(_translate("MainWindow", "多層感知器(MLP)"))
        self.menuAdaboost.setTitle(_translate("MainWindow", "自適應增強(Adaboost)"))
        self.menu_Open.setTitle(_translate("MainWindow", "開啟"))
        self.menu_About.setTitle(_translate("MainWindow", "關於"))
        self.menu_Webcrawler.setTitle(_translate("MainWindow", "網路爬蟲"))
        self.menuinformation.setTitle(_translate("MainWindow", "查看資訊"))
        self.menu_Reports.setTitle(_translate("MainWindow", "績效報告"))
        self.actionTurtle30k.setText(_translate("MainWindow", "海龜30k策略集"))
        self.actionTurtle60k.setText(_translate("MainWindow", "海龜60k策略集"))
        self.actionMulticharts.setText(_translate("MainWindow", "Multicharts"))
        self.actionAbout.setText(_translate("MainWindow", "關於我們"))
        self.actionAboutMC.setText(_translate("MainWindow", "關於Multicharts"))
        self.actionrecentInfo.setText(_translate("MainWindow", "近期期貨新聞"))
        self.actionMA_Original.setText(_translate("MainWindow", "移動均線策略集"))
        self.actionGetData.setText(_translate("MainWindow", "抓取資料"))
        self.actionTranningMachine.setText(_translate("MainWindow", "訓練機器"))
        self.actionDT_Original.setText(_translate("MainWindow", "原始DT"))
        self.actionDT_Kelly.setText(_translate("MainWindow", "DT＋凱利"))
        self.actionDT_FixedRatio.setText(_translate("MainWindow", "DT＋固定比例"))
        self.actionDT_OptimalF.setText(_translate("MainWindow", "DT＋最佳F值"))
        self.actionDT_LarryWilliams.setText(_translate("MainWindow", "DT＋LarryWilliams"))
        self.actionDT_AntiMartingale.setText(_translate("MainWindow", "DT＋反馬丁格"))
        self.actionLSTM_Original.setText(_translate("MainWindow", "原始LSTM"))
        self.actionLSTM_Kelly.setText(_translate("MainWindow", "LSTM＋凱利"))
        self.actionLSTM_FixedRatio.setText(_translate("MainWindow", "LSTM＋固定比率"))
        self.actionLSTM_OptimalF.setText(_translate("MainWindow", "LSTM＋最佳F值"))
        self.actionLSTM_LarryWilliams.setText(_translate("MainWindow", "LSTM＋LarryWilliams"))
        self.actionLSTM_AntiMartingale.setText(_translate("MainWindow", "LSTM＋反馬丁格"))
        self.actionRF_Original.setText(_translate("MainWindow", "原始RF"))
        self.actionRF_Kelly.setText(_translate("MainWindow", "RF＋凱利"))
        self.actionRF_FixedRatio.setText(_translate("MainWindow", "RF＋固定比率"))
        self.actionRF_OptimalF.setText(_translate("MainWindow", "RF＋最佳F值"))
        self.actionRF_LarryWilliams.setText(_translate("MainWindow", "RF＋LarryWilliams"))
        self.actionRF_AntiMartingale.setText(_translate("MainWindow", "RF＋反馬丁格"))
        self.actionMLP_Original.setText(_translate("MainWindow", "原始MLP"))
        self.actionMLP_Kelly.setText(_translate("MainWindow", "MLP＋凱利"))
        self.actionMLP_FixedRatio.setText(_translate("MainWindow", "MLP＋固定比率"))
        self.actionMLP_OptimalF.setText(_translate("MainWindow", "MLP＋最佳F值"))
        self.actionMLP_LarryWilliams.setText(_translate("MainWindow", "MLP＋LarryWilliams"))
        self.actionMLP_AntiMartingale.setText(_translate("MainWindow", "MLP＋反馬丁格"))
        self.actionAdaboost_Original.setText(_translate("MainWindow", "原始Adaboost"))
        self.actionAdaboost_Kelly.setText(_translate("MainWindow", "Adaboost＋凱利"))
        self.actionAdaboost_FixedRatio.setText(_translate("MainWindow", "Adaboost＋固定比率"))
        self.actionAdaboost_OptimalF.setText(_translate("MainWindow", "Adaboost＋最佳F值"))
        self.actionAdaboost_LarryWilliams.setText(_translate("MainWindow", "Adaboost＋LarryWilliams"))
        self.actionAdaboost_AntiMartingale.setText(_translate("MainWindow", "Adaboost＋反馬丁格"))
        self.actionRangeBreak_Original.setText(_translate("MainWindow", "區間突破策略集"))
        self.actionPowerLanguage_Editor.setText(_translate("MainWindow", "PowerLanguage Editor"))