# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MLP_UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(747, 643)
        Form.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.label_9 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.choseDataBtn = QtWidgets.QToolButton(Form)
        self.choseDataBtn.setObjectName("choseDataBtn")
        self.horizontalLayout_2.addWidget(self.choseDataBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.startTrainBtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startTrainBtn.sizePolicy().hasHeightForWidth())
        self.startTrainBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.startTrainBtn.setFont(font)
        self.startTrainBtn.setObjectName("startTrainBtn")
        self.verticalLayout_3.addWidget(self.startTrainBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.profitCol = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.profitCol.setFont(font)
        self.profitCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.profitCol.setObjectName("profitCol")
        self.verticalLayout_2.addWidget(self.profitCol)
        self.winrateCol = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.winrateCol.setFont(font)
        self.winrateCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.winrateCol.setObjectName("winrateCol")
        self.verticalLayout_2.addWidget(self.winrateCol)
        self.winLossCol = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.winLossCol.setFont(font)
        self.winLossCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.winLossCol.setObjectName("winLossCol")
        self.verticalLayout_2.addWidget(self.winLossCol)
        self.profitFactorCol = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.profitFactorCol.setFont(font)
        self.profitFactorCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.profitFactorCol.setObjectName("profitFactorCol")
        self.verticalLayout_2.addWidget(self.profitFactorCol)
        self.mddCol = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.mddCol.setFont(font)
        self.mddCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mddCol.setObjectName("mddCol")
        self.verticalLayout_2.addWidget(self.mddCol)
        self.sharpeCol = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.sharpeCol.setFont(font)
        self.sharpeCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sharpeCol.setObjectName("sharpeCol")
        self.verticalLayout_2.addWidget(self.sharpeCol)
        self.costCol = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.costCol.setFont(font)
        self.costCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.costCol.setObjectName("costCol")
        self.verticalLayout_2.addWidget(self.costCol)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.profitOut = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.profitOut.setFont(font)
        self.profitOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.profitOut.setObjectName("profitOut")
        self.verticalLayout_5.addWidget(self.profitOut)
        self.winRateOut = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.winRateOut.setFont(font)
        self.winRateOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.winRateOut.setObjectName("winRateOut")
        self.verticalLayout_5.addWidget(self.winRateOut)
        self.winLossOut = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.winLossOut.setFont(font)
        self.winLossOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.winLossOut.setObjectName("winLossOut")
        self.verticalLayout_5.addWidget(self.winLossOut)
        self.profitFactorOut = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.profitFactorOut.setFont(font)
        self.profitFactorOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.profitFactorOut.setObjectName("profitFactorOut")
        self.verticalLayout_5.addWidget(self.profitFactorOut)
        self.mddOut = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.mddOut.setFont(font)
        self.mddOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mddOut.setObjectName("mddOut")
        self.verticalLayout_5.addWidget(self.mddOut)
        self.tradeCuntOut = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.tradeCuntOut.setFont(font)
        self.tradeCuntOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tradeCuntOut.setObjectName("tradeCuntOut")
        self.verticalLayout_5.addWidget(self.tradeCuntOut)
        self.costOut = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.costOut.setFont(font)
        self.costOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.costOut.setObjectName("costOut")
        self.verticalLayout_5.addWidget(self.costOut)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_13.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "MLP多層感知器"))
        self.label_9.setText(_translate("Form", "選擇訓練資料"))
        self.choseDataBtn.setText(_translate("Form", "..."))
        self.startTrainBtn.setText(_translate("Form", "開始訓練"))
        self.label_4.setText(_translate("Form", "績效"))
        self.profitCol.setText(_translate("Form", "淨利:"))
        self.winrateCol.setText(_translate("Form", "勝率:"))
        self.winLossCol.setText(_translate("Form", "賺賠比:"))
        self.profitFactorCol.setText(_translate("Form", "獲利因子:"))
        self.mddCol.setText(_translate("Form", "最大策略虧損:"))
        self.sharpeCol.setText(_translate("Form", "總交易次數:"))
        self.costCol.setText(_translate("Form", "交易成本:"))
        self.profitOut.setText(_translate("Form", "─"))
        self.winRateOut.setText(_translate("Form", "─"))
        self.winLossOut.setText(_translate("Form", "─"))
        self.profitFactorOut.setText(_translate("Form", "─"))
        self.mddOut.setText(_translate("Form", "─"))
        self.tradeCuntOut.setText(_translate("Form", "─"))
        self.costOut.setText(_translate("Form", "─"))
