# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Performance_UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(906, 543)
        self.gridLayout_2 = QtWidgets.QGridLayout(widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(widget)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget.setGridStyle(QtCore.Qt.DashDotLine)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.gridLayout_2.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(widget)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("widget", "原始策略"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("widget", "凱利公式"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("widget", "固定比率"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("widget", "最佳F值"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("widget", "LarryWilliam"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("widget", "反馬丁格"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("widget", "淨利"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("widget", "勝率"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("widget", "賺賠比"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("widget", "獲利因子"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("widget", "最大策略虧損"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("widget", "總交易次數"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("widget", "夏普比率"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("widget", "交易成本or滑價金額"))
        self.label.setText(_translate("widget", "海龜"))
