# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Read_txt_UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(780, 656)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setSizeIncrement(QtCore.QSize(600, 600))
        Form.setStyleSheet("background-color: rgb(242, 242, 242);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.toolButton = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.toolButton.setFont(font)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_2.addWidget(self.toolButton)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.toolButton_2 = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_2.setObjectName("toolButton_2")
        self.verticalLayout_2.addWidget(self.toolButton_2)
        self.line_10 = QtWidgets.QFrame(self.frame)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_2.addWidget(self.line_10)
        self.toolButton_3 = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_3.setObjectName("toolButton_3")
        self.verticalLayout_2.addWidget(self.toolButton_3)
        self.line_19 = QtWidgets.QFrame(self.frame)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.verticalLayout_2.addWidget(self.line_19)
        self.toolButton_4 = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_4.sizePolicy().hasHeightForWidth())
        self.toolButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_4.setObjectName("toolButton_4")
        self.verticalLayout_2.addWidget(self.toolButton_4)
        self.line_28 = QtWidgets.QFrame(self.frame)
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.verticalLayout_2.addWidget(self.line_28)
        self.toolButton_5 = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_5.sizePolicy().hasHeightForWidth())
        self.toolButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.toolButton_5.setFont(font)
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_5.setObjectName("toolButton_5")
        self.verticalLayout_2.addWidget(self.toolButton_5)
        self.line_29 = QtWidgets.QFrame(self.frame)
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.verticalLayout_2.addWidget(self.line_29)
        self.toolButton_6 = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_6.sizePolicy().hasHeightForWidth())
        self.toolButton_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.toolButton_6.setFont(font)
        self.toolButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_6.setObjectName("toolButton_6")
        self.verticalLayout_2.addWidget(self.toolButton_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.strategy_1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.strategy_1.setFont(font)
        self.strategy_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.strategy_1.setObjectName("strategy_1")
        self.verticalLayout.addWidget(self.strategy_1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.strategy_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.strategy_2.setFont(font)
        self.strategy_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.strategy_2.setObjectName("strategy_2")
        self.verticalLayout.addWidget(self.strategy_2)
        self.line_11 = QtWidgets.QFrame(self.frame)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout.addWidget(self.line_11)
        self.strategy_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.strategy_3.setFont(font)
        self.strategy_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.strategy_3.setObjectName("strategy_3")
        self.verticalLayout.addWidget(self.strategy_3)
        self.line_20 = QtWidgets.QFrame(self.frame)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.verticalLayout.addWidget(self.line_20)
        self.strategy_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.strategy_4.setFont(font)
        self.strategy_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.strategy_4.setObjectName("strategy_4")
        self.verticalLayout.addWidget(self.strategy_4)
        self.line_30 = QtWidgets.QFrame(self.frame)
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.verticalLayout.addWidget(self.line_30)
        self.strategy_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.strategy_5.setFont(font)
        self.strategy_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.strategy_5.setObjectName("strategy_5")
        self.verticalLayout.addWidget(self.strategy_5)
        self.line_31 = QtWidgets.QFrame(self.frame)
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.verticalLayout.addWidget(self.line_31)
        self.strategy_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.strategy_6.setFont(font)
        self.strategy_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.strategy_6.setObjectName("strategy_6")
        self.verticalLayout.addWidget(self.strategy_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.st1_1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st1_1.setFont(font)
        self.st1_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st1_1.setObjectName("st1_1")
        self.verticalLayout_3.addWidget(self.st1_1)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.st2_1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st2_1.setFont(font)
        self.st2_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st2_1.setObjectName("st2_1")
        self.verticalLayout_3.addWidget(self.st2_1)
        self.line_12 = QtWidgets.QFrame(self.frame)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_3.addWidget(self.line_12)
        self.st3_1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st3_1.setFont(font)
        self.st3_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st3_1.setObjectName("st3_1")
        self.verticalLayout_3.addWidget(self.st3_1)
        self.line_21 = QtWidgets.QFrame(self.frame)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.verticalLayout_3.addWidget(self.line_21)
        self.st4_1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st4_1.setFont(font)
        self.st4_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st4_1.setObjectName("st4_1")
        self.verticalLayout_3.addWidget(self.st4_1)
        self.line_32 = QtWidgets.QFrame(self.frame)
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.verticalLayout_3.addWidget(self.line_32)
        self.st5_1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st5_1.setFont(font)
        self.st5_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st5_1.setObjectName("st5_1")
        self.verticalLayout_3.addWidget(self.st5_1)
        self.line_33 = QtWidgets.QFrame(self.frame)
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.verticalLayout_3.addWidget(self.line_33)
        self.st6_1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st6_1.setFont(font)
        self.st6_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st6_1.setObjectName("st6_1")
        self.verticalLayout_3.addWidget(self.st6_1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.st1_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st1_2.setFont(font)
        self.st1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st1_2.setObjectName("st1_2")
        self.verticalLayout_4.addWidget(self.st1_2)
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.st2_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st2_2.setFont(font)
        self.st2_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st2_2.setObjectName("st2_2")
        self.verticalLayout_4.addWidget(self.st2_2)
        self.line_13 = QtWidgets.QFrame(self.frame)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_4.addWidget(self.line_13)
        self.st3_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st3_2.setFont(font)
        self.st3_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st3_2.setObjectName("st3_2")
        self.verticalLayout_4.addWidget(self.st3_2)
        self.line_22 = QtWidgets.QFrame(self.frame)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.verticalLayout_4.addWidget(self.line_22)
        self.st4_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st4_2.setFont(font)
        self.st4_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st4_2.setObjectName("st4_2")
        self.verticalLayout_4.addWidget(self.st4_2)
        self.line_34 = QtWidgets.QFrame(self.frame)
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.verticalLayout_4.addWidget(self.line_34)
        self.st5_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st5_2.setFont(font)
        self.st5_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st5_2.setObjectName("st5_2")
        self.verticalLayout_4.addWidget(self.st5_2)
        self.line_35 = QtWidgets.QFrame(self.frame)
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.verticalLayout_4.addWidget(self.line_35)
        self.st6_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st6_2.setFont(font)
        self.st6_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st6_2.setObjectName("st6_2")
        self.verticalLayout_4.addWidget(self.st6_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.st1_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st1_3.setFont(font)
        self.st1_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st1_3.setObjectName("st1_3")
        self.verticalLayout_5.addWidget(self.st1_3)
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_5.addWidget(self.line_5)
        self.st2_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st2_3.setFont(font)
        self.st2_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st2_3.setObjectName("st2_3")
        self.verticalLayout_5.addWidget(self.st2_3)
        self.line_14 = QtWidgets.QFrame(self.frame)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_5.addWidget(self.line_14)
        self.st3_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st3_3.setFont(font)
        self.st3_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st3_3.setObjectName("st3_3")
        self.verticalLayout_5.addWidget(self.st3_3)
        self.line_23 = QtWidgets.QFrame(self.frame)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.verticalLayout_5.addWidget(self.line_23)
        self.st4_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st4_3.setFont(font)
        self.st4_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st4_3.setObjectName("st4_3")
        self.verticalLayout_5.addWidget(self.st4_3)
        self.line_36 = QtWidgets.QFrame(self.frame)
        self.line_36.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.verticalLayout_5.addWidget(self.line_36)
        self.st5_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st5_3.setFont(font)
        self.st5_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st5_3.setObjectName("st5_3")
        self.verticalLayout_5.addWidget(self.st5_3)
        self.line_37 = QtWidgets.QFrame(self.frame)
        self.line_37.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.verticalLayout_5.addWidget(self.line_37)
        self.st6_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st6_3.setFont(font)
        self.st6_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st6_3.setObjectName("st6_3")
        self.verticalLayout_5.addWidget(self.st6_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.st1_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st1_4.setFont(font)
        self.st1_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st1_4.setObjectName("st1_4")
        self.verticalLayout_6.addWidget(self.st1_4)
        self.line_6 = QtWidgets.QFrame(self.frame)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_6.addWidget(self.line_6)
        self.st2_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st2_4.setFont(font)
        self.st2_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st2_4.setObjectName("st2_4")
        self.verticalLayout_6.addWidget(self.st2_4)
        self.line_15 = QtWidgets.QFrame(self.frame)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_6.addWidget(self.line_15)
        self.st3_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st3_4.setFont(font)
        self.st3_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st3_4.setObjectName("st3_4")
        self.verticalLayout_6.addWidget(self.st3_4)
        self.line_24 = QtWidgets.QFrame(self.frame)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.verticalLayout_6.addWidget(self.line_24)
        self.st4_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st4_4.setFont(font)
        self.st4_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st4_4.setObjectName("st4_4")
        self.verticalLayout_6.addWidget(self.st4_4)
        self.line_38 = QtWidgets.QFrame(self.frame)
        self.line_38.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.verticalLayout_6.addWidget(self.line_38)
        self.st5_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st5_4.setFont(font)
        self.st5_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st5_4.setObjectName("st5_4")
        self.verticalLayout_6.addWidget(self.st5_4)
        self.line_39 = QtWidgets.QFrame(self.frame)
        self.line_39.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.verticalLayout_6.addWidget(self.line_39)
        self.st6_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st6_4.setFont(font)
        self.st6_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st6_4.setObjectName("st6_4")
        self.verticalLayout_6.addWidget(self.st6_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.st1_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st1_5.setFont(font)
        self.st1_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st1_5.setObjectName("st1_5")
        self.verticalLayout_7.addWidget(self.st1_5)
        self.line_7 = QtWidgets.QFrame(self.frame)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_7.addWidget(self.line_7)
        self.st2_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st2_5.setFont(font)
        self.st2_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st2_5.setObjectName("st2_5")
        self.verticalLayout_7.addWidget(self.st2_5)
        self.line_16 = QtWidgets.QFrame(self.frame)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_7.addWidget(self.line_16)
        self.st3_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st3_5.setFont(font)
        self.st3_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st3_5.setObjectName("st3_5")
        self.verticalLayout_7.addWidget(self.st3_5)
        self.line_25 = QtWidgets.QFrame(self.frame)
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.verticalLayout_7.addWidget(self.line_25)
        self.st4_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st4_5.setFont(font)
        self.st4_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st4_5.setObjectName("st4_5")
        self.verticalLayout_7.addWidget(self.st4_5)
        self.line_40 = QtWidgets.QFrame(self.frame)
        self.line_40.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.verticalLayout_7.addWidget(self.line_40)
        self.st5_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st5_5.setFont(font)
        self.st5_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st5_5.setObjectName("st5_5")
        self.verticalLayout_7.addWidget(self.st5_5)
        self.line_41 = QtWidgets.QFrame(self.frame)
        self.line_41.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.verticalLayout_7.addWidget(self.line_41)
        self.st6_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st6_5.setFont(font)
        self.st6_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st6_5.setObjectName("st6_5")
        self.verticalLayout_7.addWidget(self.st6_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.st1_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st1_6.setFont(font)
        self.st1_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st1_6.setObjectName("st1_6")
        self.verticalLayout_8.addWidget(self.st1_6)
        self.line_8 = QtWidgets.QFrame(self.frame)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_8.addWidget(self.line_8)
        self.st2_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st2_6.setFont(font)
        self.st2_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st2_6.setObjectName("st2_6")
        self.verticalLayout_8.addWidget(self.st2_6)
        self.line_17 = QtWidgets.QFrame(self.frame)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.verticalLayout_8.addWidget(self.line_17)
        self.st3_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st3_6.setFont(font)
        self.st3_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st3_6.setObjectName("st3_6")
        self.verticalLayout_8.addWidget(self.st3_6)
        self.line_26 = QtWidgets.QFrame(self.frame)
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.verticalLayout_8.addWidget(self.line_26)
        self.st4_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st4_6.setFont(font)
        self.st4_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st4_6.setObjectName("st4_6")
        self.verticalLayout_8.addWidget(self.st4_6)
        self.line_42 = QtWidgets.QFrame(self.frame)
        self.line_42.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.verticalLayout_8.addWidget(self.line_42)
        self.st5_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st5_6.setFont(font)
        self.st5_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st5_6.setObjectName("st5_6")
        self.verticalLayout_8.addWidget(self.st5_6)
        self.line_43 = QtWidgets.QFrame(self.frame)
        self.line_43.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.verticalLayout_8.addWidget(self.line_43)
        self.st6_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st6_6.setFont(font)
        self.st6_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st6_6.setObjectName("st6_6")
        self.verticalLayout_8.addWidget(self.st6_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.st1_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st1_7.setFont(font)
        self.st1_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st1_7.setObjectName("st1_7")
        self.verticalLayout_9.addWidget(self.st1_7)
        self.line_9 = QtWidgets.QFrame(self.frame)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_9.addWidget(self.line_9)
        self.st2_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st2_7.setFont(font)
        self.st2_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st2_7.setObjectName("st2_7")
        self.verticalLayout_9.addWidget(self.st2_7)
        self.line_18 = QtWidgets.QFrame(self.frame)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.verticalLayout_9.addWidget(self.line_18)
        self.st3_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st3_7.setFont(font)
        self.st3_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st3_7.setObjectName("st3_7")
        self.verticalLayout_9.addWidget(self.st3_7)
        self.line_27 = QtWidgets.QFrame(self.frame)
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.verticalLayout_9.addWidget(self.line_27)
        self.st4_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st4_7.setFont(font)
        self.st4_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st4_7.setObjectName("st4_7")
        self.verticalLayout_9.addWidget(self.st4_7)
        self.line_44 = QtWidgets.QFrame(self.frame)
        self.line_44.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.verticalLayout_9.addWidget(self.line_44)
        self.st5_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st5_7.setFont(font)
        self.st5_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st5_7.setObjectName("st5_7")
        self.verticalLayout_9.addWidget(self.st5_7)
        self.line_45 = QtWidgets.QFrame(self.frame)
        self.line_45.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.verticalLayout_9.addWidget(self.line_45)
        self.st6_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.st6_7.setFont(font)
        self.st6_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st6_7.setObjectName("st6_7")
        self.verticalLayout_9.addWidget(self.st6_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_11.setText(_translate("Form", "請選擇策略"))
        self.toolButton.setText(_translate("Form", "第一項"))
        self.toolButton_2.setText(_translate("Form", "第二項"))
        self.toolButton_3.setText(_translate("Form", "第三項"))
        self.toolButton_4.setText(_translate("Form", "第四項"))
        self.toolButton_5.setText(_translate("Form", "第五項"))
        self.toolButton_6.setText(_translate("Form", "第六項"))
        self.title.setText(_translate("Form", "策略名稱"))
        self.strategy_1.setText(_translate("Form", "N/A"))
        self.strategy_2.setText(_translate("Form", "N/A"))
        self.strategy_3.setText(_translate("Form", "N/A"))
        self.strategy_4.setText(_translate("Form", "N/A"))
        self.strategy_5.setText(_translate("Form", "N/A"))
        self.strategy_6.setText(_translate("Form", "N/A"))
        self.label.setText(_translate("Form", "淨利"))
        self.st1_1.setText(_translate("Form", "n/a"))
        self.st2_1.setText(_translate("Form", "n/a"))
        self.st3_1.setText(_translate("Form", "n/a"))
        self.st4_1.setText(_translate("Form", "n/a"))
        self.st5_1.setText(_translate("Form", "n/a"))
        self.st6_1.setText(_translate("Form", "n/a"))
        self.label_2.setText(_translate("Form", "勝率"))
        self.st1_2.setText(_translate("Form", "n/a"))
        self.st2_2.setText(_translate("Form", "n/a"))
        self.st3_2.setText(_translate("Form", "n/a"))
        self.st4_2.setText(_translate("Form", "n/a"))
        self.st5_2.setText(_translate("Form", "n/a"))
        self.st6_2.setText(_translate("Form", "n/a"))
        self.label_3.setText(_translate("Form", "賺賠比"))
        self.st1_3.setText(_translate("Form", "n/a"))
        self.st2_3.setText(_translate("Form", "n/a"))
        self.st3_3.setText(_translate("Form", "n/a"))
        self.st4_3.setText(_translate("Form", "n/a"))
        self.st5_3.setText(_translate("Form", "n/a"))
        self.st6_3.setText(_translate("Form", "n/a"))
        self.label_4.setText(_translate("Form", "獲利因子"))
        self.st1_4.setText(_translate("Form", "n/a"))
        self.st2_4.setText(_translate("Form", "n/a"))
        self.st3_4.setText(_translate("Form", "n/a"))
        self.st4_4.setText(_translate("Form", "n/a"))
        self.st5_4.setText(_translate("Form", "n/a"))
        self.st6_4.setText(_translate("Form", "n/a"))
        self.label_5.setText(_translate("Form", "最大策略虧損"))
        self.st1_5.setText(_translate("Form", "n/a"))
        self.st2_5.setText(_translate("Form", "n/a"))
        self.st3_5.setText(_translate("Form", "n/a"))
        self.st4_5.setText(_translate("Form", "n/a"))
        self.st5_5.setText(_translate("Form", "n/a"))
        self.st6_5.setText(_translate("Form", "n/a"))
        self.label_6.setText(_translate("Form", "總交易次數"))
        self.st1_6.setText(_translate("Form", "n/a"))
        self.st2_6.setText(_translate("Form", "n/a"))
        self.st3_6.setText(_translate("Form", "n/a"))
        self.st4_6.setText(_translate("Form", "n/a"))
        self.st5_6.setText(_translate("Form", "n/a"))
        self.st6_6.setText(_translate("Form", "n/a"))
        self.label_7.setText(_translate("Form", "交易成本"))
        self.st1_7.setText(_translate("Form", "n/a"))
        self.st2_7.setText(_translate("Form", "n/a"))
        self.st3_7.setText(_translate("Form", "n/a"))
        self.st4_7.setText(_translate("Form", "n/a"))
        self.st5_7.setText(_translate("Form", "n/a"))
        self.st6_7.setText(_translate("Form", "n/a"))
