# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Read_txt_UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(714, 629)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setSizeIncrement(QtCore.QSize(600, 600))
        Form.setStyleSheet("background-color: rgb(242, 242, 242);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.toolButton = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_2.addWidget(self.toolButton)
        self.toolButton_2 = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_2.setObjectName("toolButton_2")
        self.verticalLayout_2.addWidget(self.toolButton_2)
        self.toolButton_3 = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_3.setObjectName("toolButton_3")
        self.verticalLayout_2.addWidget(self.toolButton_3)
        self.toolButton_4 = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_4.sizePolicy().hasHeightForWidth())
        self.toolButton_4.setSizePolicy(sizePolicy)
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_4.setObjectName("toolButton_4")
        self.verticalLayout_2.addWidget(self.toolButton_4)
        self.toolButton_5 = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_5.sizePolicy().hasHeightForWidth())
        self.toolButton_5.setSizePolicy(sizePolicy)
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_5.setObjectName("toolButton_5")
        self.verticalLayout_2.addWidget(self.toolButton_5)
        self.toolButton_6 = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_6.sizePolicy().hasHeightForWidth())
        self.toolButton_6.setSizePolicy(sizePolicy)
        self.toolButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_6.setObjectName("toolButton_6")
        self.verticalLayout_2.addWidget(self.toolButton_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.strategy_1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.strategy_1.setFont(font)
        self.strategy_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.strategy_1.setObjectName("strategy_1")
        self.verticalLayout.addWidget(self.strategy_1)
        self.strategy_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.strategy_2.setFont(font)
        self.strategy_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.strategy_2.setObjectName("strategy_2")
        self.verticalLayout.addWidget(self.strategy_2)
        self.strategy_3 = QtWidgets.QLabel(self.frame)
        self.strategy_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.strategy_3.setObjectName("strategy_3")
        self.verticalLayout.addWidget(self.strategy_3)
        self.strategy_4 = QtWidgets.QLabel(self.frame)
        self.strategy_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.strategy_4.setObjectName("strategy_4")
        self.verticalLayout.addWidget(self.strategy_4)
        self.strategy_5 = QtWidgets.QLabel(self.frame)
        self.strategy_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.strategy_5.setObjectName("strategy_5")
        self.verticalLayout.addWidget(self.strategy_5)
        self.strategy_6 = QtWidgets.QLabel(self.frame)
        self.strategy_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.strategy_6.setObjectName("strategy_6")
        self.verticalLayout.addWidget(self.strategy_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.st1_1 = QtWidgets.QLabel(self.frame)
        self.st1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.st1_1.setObjectName("st1_1")
        self.verticalLayout_3.addWidget(self.st1_1)
        self.st2_1 = QtWidgets.QLabel(self.frame)
        self.st2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.st2_1.setObjectName("st2_1")
        self.verticalLayout_3.addWidget(self.st2_1)
        self.st3_1 = QtWidgets.QLabel(self.frame)
        self.st3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.st3_1.setObjectName("st3_1")
        self.verticalLayout_3.addWidget(self.st3_1)
        self.st4_1 = QtWidgets.QLabel(self.frame)
        self.st4_1.setAlignment(QtCore.Qt.AlignCenter)
        self.st4_1.setObjectName("st4_1")
        self.verticalLayout_3.addWidget(self.st4_1)
        self.st5_1 = QtWidgets.QLabel(self.frame)
        self.st5_1.setAlignment(QtCore.Qt.AlignCenter)
        self.st5_1.setObjectName("st5_1")
        self.verticalLayout_3.addWidget(self.st5_1)
        self.st6_1 = QtWidgets.QLabel(self.frame)
        self.st6_1.setAlignment(QtCore.Qt.AlignCenter)
        self.st6_1.setObjectName("st6_1")
        self.verticalLayout_3.addWidget(self.st6_1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.st1_2 = QtWidgets.QLabel(self.frame)
        self.st1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.st1_2.setObjectName("st1_2")
        self.verticalLayout_4.addWidget(self.st1_2)
        self.st2_2 = QtWidgets.QLabel(self.frame)
        self.st2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.st2_2.setObjectName("st2_2")
        self.verticalLayout_4.addWidget(self.st2_2)
        self.st3_2 = QtWidgets.QLabel(self.frame)
        self.st3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.st3_2.setObjectName("st3_2")
        self.verticalLayout_4.addWidget(self.st3_2)
        self.st4_2 = QtWidgets.QLabel(self.frame)
        self.st4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.st4_2.setObjectName("st4_2")
        self.verticalLayout_4.addWidget(self.st4_2)
        self.st5_2 = QtWidgets.QLabel(self.frame)
        self.st5_2.setAlignment(QtCore.Qt.AlignCenter)
        self.st5_2.setObjectName("st5_2")
        self.verticalLayout_4.addWidget(self.st5_2)
        self.st6_2 = QtWidgets.QLabel(self.frame)
        self.st6_2.setAlignment(QtCore.Qt.AlignCenter)
        self.st6_2.setObjectName("st6_2")
        self.verticalLayout_4.addWidget(self.st6_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.st1_3 = QtWidgets.QLabel(self.frame)
        self.st1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.st1_3.setObjectName("st1_3")
        self.verticalLayout_5.addWidget(self.st1_3)
        self.st2_3 = QtWidgets.QLabel(self.frame)
        self.st2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.st2_3.setObjectName("st2_3")
        self.verticalLayout_5.addWidget(self.st2_3)
        self.st3_3 = QtWidgets.QLabel(self.frame)
        self.st3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.st3_3.setObjectName("st3_3")
        self.verticalLayout_5.addWidget(self.st3_3)
        self.st4_3 = QtWidgets.QLabel(self.frame)
        self.st4_3.setAlignment(QtCore.Qt.AlignCenter)
        self.st4_3.setObjectName("st4_3")
        self.verticalLayout_5.addWidget(self.st4_3)
        self.st5_3 = QtWidgets.QLabel(self.frame)
        self.st5_3.setAlignment(QtCore.Qt.AlignCenter)
        self.st5_3.setObjectName("st5_3")
        self.verticalLayout_5.addWidget(self.st5_3)
        self.st6_3 = QtWidgets.QLabel(self.frame)
        self.st6_3.setAlignment(QtCore.Qt.AlignCenter)
        self.st6_3.setObjectName("st6_3")
        self.verticalLayout_5.addWidget(self.st6_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.st1_4 = QtWidgets.QLabel(self.frame)
        self.st1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.st1_4.setObjectName("st1_4")
        self.verticalLayout_6.addWidget(self.st1_4)
        self.st2_4 = QtWidgets.QLabel(self.frame)
        self.st2_4.setAlignment(QtCore.Qt.AlignCenter)
        self.st2_4.setObjectName("st2_4")
        self.verticalLayout_6.addWidget(self.st2_4)
        self.st3_4 = QtWidgets.QLabel(self.frame)
        self.st3_4.setAlignment(QtCore.Qt.AlignCenter)
        self.st3_4.setObjectName("st3_4")
        self.verticalLayout_6.addWidget(self.st3_4)
        self.st4_4 = QtWidgets.QLabel(self.frame)
        self.st4_4.setAlignment(QtCore.Qt.AlignCenter)
        self.st4_4.setObjectName("st4_4")
        self.verticalLayout_6.addWidget(self.st4_4)
        self.st5_4 = QtWidgets.QLabel(self.frame)
        self.st5_4.setAlignment(QtCore.Qt.AlignCenter)
        self.st5_4.setObjectName("st5_4")
        self.verticalLayout_6.addWidget(self.st5_4)
        self.st6_4 = QtWidgets.QLabel(self.frame)
        self.st6_4.setAlignment(QtCore.Qt.AlignCenter)
        self.st6_4.setObjectName("st6_4")
        self.verticalLayout_6.addWidget(self.st6_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.st1_5 = QtWidgets.QLabel(self.frame)
        self.st1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.st1_5.setObjectName("st1_5")
        self.verticalLayout_7.addWidget(self.st1_5)
        self.st2_5 = QtWidgets.QLabel(self.frame)
        self.st2_5.setAlignment(QtCore.Qt.AlignCenter)
        self.st2_5.setObjectName("st2_5")
        self.verticalLayout_7.addWidget(self.st2_5)
        self.st3_5 = QtWidgets.QLabel(self.frame)
        self.st3_5.setAlignment(QtCore.Qt.AlignCenter)
        self.st3_5.setObjectName("st3_5")
        self.verticalLayout_7.addWidget(self.st3_5)
        self.st4_5 = QtWidgets.QLabel(self.frame)
        self.st4_5.setAlignment(QtCore.Qt.AlignCenter)
        self.st4_5.setObjectName("st4_5")
        self.verticalLayout_7.addWidget(self.st4_5)
        self.st5_5 = QtWidgets.QLabel(self.frame)
        self.st5_5.setAlignment(QtCore.Qt.AlignCenter)
        self.st5_5.setObjectName("st5_5")
        self.verticalLayout_7.addWidget(self.st5_5)
        self.st6_5 = QtWidgets.QLabel(self.frame)
        self.st6_5.setAlignment(QtCore.Qt.AlignCenter)
        self.st6_5.setObjectName("st6_5")
        self.verticalLayout_7.addWidget(self.st6_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.st1_6 = QtWidgets.QLabel(self.frame)
        self.st1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.st1_6.setObjectName("st1_6")
        self.verticalLayout_8.addWidget(self.st1_6)
        self.st2_6 = QtWidgets.QLabel(self.frame)
        self.st2_6.setAlignment(QtCore.Qt.AlignCenter)
        self.st2_6.setObjectName("st2_6")
        self.verticalLayout_8.addWidget(self.st2_6)
        self.st3_6 = QtWidgets.QLabel(self.frame)
        self.st3_6.setAlignment(QtCore.Qt.AlignCenter)
        self.st3_6.setObjectName("st3_6")
        self.verticalLayout_8.addWidget(self.st3_6)
        self.st4_6 = QtWidgets.QLabel(self.frame)
        self.st4_6.setAlignment(QtCore.Qt.AlignCenter)
        self.st4_6.setObjectName("st4_6")
        self.verticalLayout_8.addWidget(self.st4_6)
        self.st5_6 = QtWidgets.QLabel(self.frame)
        self.st5_6.setAlignment(QtCore.Qt.AlignCenter)
        self.st5_6.setObjectName("st5_6")
        self.verticalLayout_8.addWidget(self.st5_6)
        self.st6_6 = QtWidgets.QLabel(self.frame)
        self.st6_6.setAlignment(QtCore.Qt.AlignCenter)
        self.st6_6.setObjectName("st6_6")
        self.verticalLayout_8.addWidget(self.st6_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.st1_7 = QtWidgets.QLabel(self.frame)
        self.st1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.st1_7.setObjectName("st1_7")
        self.verticalLayout_9.addWidget(self.st1_7)
        self.st2_7 = QtWidgets.QLabel(self.frame)
        self.st2_7.setAlignment(QtCore.Qt.AlignCenter)
        self.st2_7.setObjectName("st2_7")
        self.verticalLayout_9.addWidget(self.st2_7)
        self.st3_7 = QtWidgets.QLabel(self.frame)
        self.st3_7.setAlignment(QtCore.Qt.AlignCenter)
        self.st3_7.setObjectName("st3_7")
        self.verticalLayout_9.addWidget(self.st3_7)
        self.st4_7 = QtWidgets.QLabel(self.frame)
        self.st4_7.setAlignment(QtCore.Qt.AlignCenter)
        self.st4_7.setObjectName("st4_7")
        self.verticalLayout_9.addWidget(self.st4_7)
        self.st5_7 = QtWidgets.QLabel(self.frame)
        self.st5_7.setAlignment(QtCore.Qt.AlignCenter)
        self.st5_7.setObjectName("st5_7")
        self.verticalLayout_9.addWidget(self.st5_7)
        self.st6_7 = QtWidgets.QLabel(self.frame)
        self.st6_7.setAlignment(QtCore.Qt.AlignCenter)
        self.st6_7.setObjectName("st6_7")
        self.verticalLayout_9.addWidget(self.st6_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_11.setText(_translate("Form", "請選擇策略"))
        self.toolButton.setText(_translate("Form", "第一項"))
        self.toolButton_2.setText(_translate("Form", "第二項"))
        self.toolButton_3.setText(_translate("Form", "第三項"))
        self.toolButton_4.setText(_translate("Form", "第四項"))
        self.toolButton_5.setText(_translate("Form", "第五項"))
        self.toolButton_6.setText(_translate("Form", "第六項"))
        self.title.setText(_translate("Form", "策略名稱"))
        self.strategy_1.setText(_translate("Form", "N/A"))
        self.strategy_2.setText(_translate("Form", "N/A"))
        self.strategy_3.setText(_translate("Form", "N/A"))
        self.strategy_4.setText(_translate("Form", "N/A"))
        self.strategy_5.setText(_translate("Form", "N/A"))
        self.strategy_6.setText(_translate("Form", "N/A"))
        self.label.setText(_translate("Form", "淨利"))
        self.st1_1.setText(_translate("Form", "n/a"))
        self.st2_1.setText(_translate("Form", "n/a"))
        self.st3_1.setText(_translate("Form", "n/a"))
        self.st4_1.setText(_translate("Form", "n/a"))
        self.st5_1.setText(_translate("Form", "n/a"))
        self.st6_1.setText(_translate("Form", "n/a"))
        self.label_2.setText(_translate("Form", "勝率"))
        self.st1_2.setText(_translate("Form", "n/a"))
        self.st2_2.setText(_translate("Form", "n/a"))
        self.st3_2.setText(_translate("Form", "n/a"))
        self.st4_2.setText(_translate("Form", "n/a"))
        self.st5_2.setText(_translate("Form", "n/a"))
        self.st6_2.setText(_translate("Form", "n/a"))
        self.label_3.setText(_translate("Form", "賺賠比"))
        self.st1_3.setText(_translate("Form", "n/a"))
        self.st2_3.setText(_translate("Form", "n/a"))
        self.st3_3.setText(_translate("Form", "n/a"))
        self.st4_3.setText(_translate("Form", "n/a"))
        self.st5_3.setText(_translate("Form", "n/a"))
        self.st6_3.setText(_translate("Form", "n/a"))
        self.label_4.setText(_translate("Form", "獲利因子"))
        self.st1_4.setText(_translate("Form", "n/a"))
        self.st2_4.setText(_translate("Form", "n/a"))
        self.st3_4.setText(_translate("Form", "n/a"))
        self.st4_4.setText(_translate("Form", "n/a"))
        self.st5_4.setText(_translate("Form", "n/a"))
        self.st6_4.setText(_translate("Form", "n/a"))
        self.label_5.setText(_translate("Form", "最大策略虧損"))
        self.st1_5.setText(_translate("Form", "n/a"))
        self.st2_5.setText(_translate("Form", "n/a"))
        self.st3_5.setText(_translate("Form", "n/a"))
        self.st4_5.setText(_translate("Form", "n/a"))
        self.st5_5.setText(_translate("Form", "n/a"))
        self.st6_5.setText(_translate("Form", "n/a"))
        self.label_6.setText(_translate("Form", "總交易次數"))
        self.st1_6.setText(_translate("Form", "n/a"))
        self.st2_6.setText(_translate("Form", "n/a"))
        self.st3_6.setText(_translate("Form", "n/a"))
        self.st4_6.setText(_translate("Form", "n/a"))
        self.st5_6.setText(_translate("Form", "n/a"))
        self.st6_6.setText(_translate("Form", "n/a"))
        self.label_7.setText(_translate("Form", "交易成本"))
        self.st1_7.setText(_translate("Form", "n/a"))
        self.st2_7.setText(_translate("Form", "n/a"))
        self.st3_7.setText(_translate("Form", "n/a"))
        self.st4_7.setText(_translate("Form", "n/a"))
        self.st5_7.setText(_translate("Form", "n/a"))
        self.st6_7.setText(_translate("Form", "n/a"))
