# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Read_txt_UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(714, 629)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setSizeIncrement(QtCore.QSize(600, 600))
        Form.setStyleSheet("background-color: rgb(242, 242, 242);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.label_9 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_10 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.origin1 = QtWidgets.QLabel(self.frame)
        self.origin1.setAlignment(QtCore.Qt.AlignCenter)
        self.origin1.setObjectName("origin1")
        self.verticalLayout_3.addWidget(self.origin1)
        self.fixratio1 = QtWidgets.QLabel(self.frame)
        self.fixratio1.setAlignment(QtCore.Qt.AlignCenter)
        self.fixratio1.setObjectName("fixratio1")
        self.verticalLayout_3.addWidget(self.fixratio1)
        self.fixfraction1 = QtWidgets.QLabel(self.frame)
        self.fixfraction1.setAlignment(QtCore.Qt.AlignCenter)
        self.fixfraction1.setObjectName("fixfraction1")
        self.verticalLayout_3.addWidget(self.fixfraction1)
        self.kelly1 = QtWidgets.QLabel(self.frame)
        self.kelly1.setAlignment(QtCore.Qt.AlignCenter)
        self.kelly1.setObjectName("kelly1")
        self.verticalLayout_3.addWidget(self.kelly1)
        self.optimal1 = QtWidgets.QLabel(self.frame)
        self.optimal1.setAlignment(QtCore.Qt.AlignCenter)
        self.optimal1.setObjectName("optimal1")
        self.verticalLayout_3.addWidget(self.optimal1)
        self.william1 = QtWidgets.QLabel(self.frame)
        self.william1.setAlignment(QtCore.Qt.AlignCenter)
        self.william1.setObjectName("william1")
        self.verticalLayout_3.addWidget(self.william1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.origin2 = QtWidgets.QLabel(self.frame)
        self.origin2.setAlignment(QtCore.Qt.AlignCenter)
        self.origin2.setObjectName("origin2")
        self.verticalLayout_4.addWidget(self.origin2)
        self.fixratio2 = QtWidgets.QLabel(self.frame)
        self.fixratio2.setAlignment(QtCore.Qt.AlignCenter)
        self.fixratio2.setObjectName("fixratio2")
        self.verticalLayout_4.addWidget(self.fixratio2)
        self.fixfraction2 = QtWidgets.QLabel(self.frame)
        self.fixfraction2.setAlignment(QtCore.Qt.AlignCenter)
        self.fixfraction2.setObjectName("fixfraction2")
        self.verticalLayout_4.addWidget(self.fixfraction2)
        self.kelly2 = QtWidgets.QLabel(self.frame)
        self.kelly2.setAlignment(QtCore.Qt.AlignCenter)
        self.kelly2.setObjectName("kelly2")
        self.verticalLayout_4.addWidget(self.kelly2)
        self.optimal2 = QtWidgets.QLabel(self.frame)
        self.optimal2.setAlignment(QtCore.Qt.AlignCenter)
        self.optimal2.setObjectName("optimal2")
        self.verticalLayout_4.addWidget(self.optimal2)
        self.william2 = QtWidgets.QLabel(self.frame)
        self.william2.setAlignment(QtCore.Qt.AlignCenter)
        self.william2.setObjectName("william2")
        self.verticalLayout_4.addWidget(self.william2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.origin3 = QtWidgets.QLabel(self.frame)
        self.origin3.setAlignment(QtCore.Qt.AlignCenter)
        self.origin3.setObjectName("origin3")
        self.verticalLayout_5.addWidget(self.origin3)
        self.fixratio3 = QtWidgets.QLabel(self.frame)
        self.fixratio3.setAlignment(QtCore.Qt.AlignCenter)
        self.fixratio3.setObjectName("fixratio3")
        self.verticalLayout_5.addWidget(self.fixratio3)
        self.fixfraction3 = QtWidgets.QLabel(self.frame)
        self.fixfraction3.setAlignment(QtCore.Qt.AlignCenter)
        self.fixfraction3.setObjectName("fixfraction3")
        self.verticalLayout_5.addWidget(self.fixfraction3)
        self.kelly3 = QtWidgets.QLabel(self.frame)
        self.kelly3.setAlignment(QtCore.Qt.AlignCenter)
        self.kelly3.setObjectName("kelly3")
        self.verticalLayout_5.addWidget(self.kelly3)
        self.optimal3 = QtWidgets.QLabel(self.frame)
        self.optimal3.setAlignment(QtCore.Qt.AlignCenter)
        self.optimal3.setObjectName("optimal3")
        self.verticalLayout_5.addWidget(self.optimal3)
        self.william3 = QtWidgets.QLabel(self.frame)
        self.william3.setAlignment(QtCore.Qt.AlignCenter)
        self.william3.setObjectName("william3")
        self.verticalLayout_5.addWidget(self.william3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.origin4 = QtWidgets.QLabel(self.frame)
        self.origin4.setAlignment(QtCore.Qt.AlignCenter)
        self.origin4.setObjectName("origin4")
        self.verticalLayout_6.addWidget(self.origin4)
        self.fixratio4 = QtWidgets.QLabel(self.frame)
        self.fixratio4.setAlignment(QtCore.Qt.AlignCenter)
        self.fixratio4.setObjectName("fixratio4")
        self.verticalLayout_6.addWidget(self.fixratio4)
        self.fixfraction4 = QtWidgets.QLabel(self.frame)
        self.fixfraction4.setAlignment(QtCore.Qt.AlignCenter)
        self.fixfraction4.setObjectName("fixfraction4")
        self.verticalLayout_6.addWidget(self.fixfraction4)
        self.kelly4 = QtWidgets.QLabel(self.frame)
        self.kelly4.setAlignment(QtCore.Qt.AlignCenter)
        self.kelly4.setObjectName("kelly4")
        self.verticalLayout_6.addWidget(self.kelly4)
        self.optimal4 = QtWidgets.QLabel(self.frame)
        self.optimal4.setAlignment(QtCore.Qt.AlignCenter)
        self.optimal4.setObjectName("optimal4")
        self.verticalLayout_6.addWidget(self.optimal4)
        self.william4 = QtWidgets.QLabel(self.frame)
        self.william4.setAlignment(QtCore.Qt.AlignCenter)
        self.william4.setObjectName("william4")
        self.verticalLayout_6.addWidget(self.william4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.origin5 = QtWidgets.QLabel(self.frame)
        self.origin5.setAlignment(QtCore.Qt.AlignCenter)
        self.origin5.setObjectName("origin5")
        self.verticalLayout_7.addWidget(self.origin5)
        self.fixratio5 = QtWidgets.QLabel(self.frame)
        self.fixratio5.setAlignment(QtCore.Qt.AlignCenter)
        self.fixratio5.setObjectName("fixratio5")
        self.verticalLayout_7.addWidget(self.fixratio5)
        self.fixfraction5 = QtWidgets.QLabel(self.frame)
        self.fixfraction5.setAlignment(QtCore.Qt.AlignCenter)
        self.fixfraction5.setObjectName("fixfraction5")
        self.verticalLayout_7.addWidget(self.fixfraction5)
        self.kelly5 = QtWidgets.QLabel(self.frame)
        self.kelly5.setAlignment(QtCore.Qt.AlignCenter)
        self.kelly5.setObjectName("kelly5")
        self.verticalLayout_7.addWidget(self.kelly5)
        self.optimal5 = QtWidgets.QLabel(self.frame)
        self.optimal5.setAlignment(QtCore.Qt.AlignCenter)
        self.optimal5.setObjectName("optimal5")
        self.verticalLayout_7.addWidget(self.optimal5)
        self.william5 = QtWidgets.QLabel(self.frame)
        self.william5.setAlignment(QtCore.Qt.AlignCenter)
        self.william5.setObjectName("william5")
        self.verticalLayout_7.addWidget(self.william5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.origin6 = QtWidgets.QLabel(self.frame)
        self.origin6.setAlignment(QtCore.Qt.AlignCenter)
        self.origin6.setObjectName("origin6")
        self.verticalLayout_8.addWidget(self.origin6)
        self.fixratio6 = QtWidgets.QLabel(self.frame)
        self.fixratio6.setAlignment(QtCore.Qt.AlignCenter)
        self.fixratio6.setObjectName("fixratio6")
        self.verticalLayout_8.addWidget(self.fixratio6)
        self.fixfraction6 = QtWidgets.QLabel(self.frame)
        self.fixfraction6.setAlignment(QtCore.Qt.AlignCenter)
        self.fixfraction6.setObjectName("fixfraction6")
        self.verticalLayout_8.addWidget(self.fixfraction6)
        self.kelly6 = QtWidgets.QLabel(self.frame)
        self.kelly6.setAlignment(QtCore.Qt.AlignCenter)
        self.kelly6.setObjectName("kelly6")
        self.verticalLayout_8.addWidget(self.kelly6)
        self.optimal6 = QtWidgets.QLabel(self.frame)
        self.optimal6.setAlignment(QtCore.Qt.AlignCenter)
        self.optimal6.setObjectName("optimal6")
        self.verticalLayout_8.addWidget(self.optimal6)
        self.william6 = QtWidgets.QLabel(self.frame)
        self.william6.setAlignment(QtCore.Qt.AlignCenter)
        self.william6.setObjectName("william6")
        self.verticalLayout_8.addWidget(self.william6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.origin7 = QtWidgets.QLabel(self.frame)
        self.origin7.setAlignment(QtCore.Qt.AlignCenter)
        self.origin7.setObjectName("origin7")
        self.verticalLayout_9.addWidget(self.origin7)
        self.fixratio7 = QtWidgets.QLabel(self.frame)
        self.fixratio7.setAlignment(QtCore.Qt.AlignCenter)
        self.fixratio7.setObjectName("fixratio7")
        self.verticalLayout_9.addWidget(self.fixratio7)
        self.fixfraction7 = QtWidgets.QLabel(self.frame)
        self.fixfraction7.setAlignment(QtCore.Qt.AlignCenter)
        self.fixfraction7.setObjectName("fixfraction7")
        self.verticalLayout_9.addWidget(self.fixfraction7)
        self.kelly7 = QtWidgets.QLabel(self.frame)
        self.kelly7.setAlignment(QtCore.Qt.AlignCenter)
        self.kelly7.setObjectName("kelly7")
        self.verticalLayout_9.addWidget(self.kelly7)
        self.optimal7 = QtWidgets.QLabel(self.frame)
        self.optimal7.setAlignment(QtCore.Qt.AlignCenter)
        self.optimal7.setObjectName("optimal7")
        self.verticalLayout_9.addWidget(self.optimal7)
        self.william7 = QtWidgets.QLabel(self.frame)
        self.william7.setAlignment(QtCore.Qt.AlignCenter)
        self.william7.setObjectName("william7")
        self.verticalLayout_9.addWidget(self.william7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "海龜30k"))
        self.label_9.setText(_translate("Form", "原始策略"))
        self.label_18.setText(_translate("Form", "固定比率"))
        self.label_8.setText(_translate("Form", "固定分數"))
        self.label_10.setText(_translate("Form", "凱利公式"))
        self.label_19.setText(_translate("Form", "最佳F值"))
        self.label_20.setText(_translate("Form", "LarryWilliams"))
        self.label.setText(_translate("Form", "淨利"))
        self.origin1.setText(_translate("Form", "TextLabel"))
        self.fixratio1.setText(_translate("Form", "TextLabel"))
        self.fixfraction1.setText(_translate("Form", "TextLabel"))
        self.kelly1.setText(_translate("Form", "TextLabel"))
        self.optimal1.setText(_translate("Form", "TextLabel"))
        self.william1.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "勝率"))
        self.origin2.setText(_translate("Form", "TextLabel"))
        self.fixratio2.setText(_translate("Form", "TextLabel"))
        self.fixfraction2.setText(_translate("Form", "TextLabel"))
        self.kelly2.setText(_translate("Form", "TextLabel"))
        self.optimal2.setText(_translate("Form", "TextLabel"))
        self.william2.setText(_translate("Form", "TextLabel"))
        self.label_3.setText(_translate("Form", "賺賠比"))
        self.origin3.setText(_translate("Form", "TextLabel"))
        self.fixratio3.setText(_translate("Form", "TextLabel"))
        self.fixfraction3.setText(_translate("Form", "TextLabel"))
        self.kelly3.setText(_translate("Form", "TextLabel"))
        self.optimal3.setText(_translate("Form", "TextLabel"))
        self.william3.setText(_translate("Form", "TextLabel"))
        self.label_4.setText(_translate("Form", "獲利因子"))
        self.origin4.setText(_translate("Form", "TextLabel"))
        self.fixratio4.setText(_translate("Form", "TextLabel"))
        self.fixfraction4.setText(_translate("Form", "TextLabel"))
        self.kelly4.setText(_translate("Form", "TextLabel"))
        self.optimal4.setText(_translate("Form", "TextLabel"))
        self.william4.setText(_translate("Form", "TextLabel"))
        self.label_5.setText(_translate("Form", "最大策略虧損"))
        self.origin5.setText(_translate("Form", "TextLabel"))
        self.fixratio5.setText(_translate("Form", "TextLabel"))
        self.fixfraction5.setText(_translate("Form", "TextLabel"))
        self.kelly5.setText(_translate("Form", "TextLabel"))
        self.optimal5.setText(_translate("Form", "TextLabel"))
        self.william5.setText(_translate("Form", "TextLabel"))
        self.label_6.setText(_translate("Form", "總交易次數"))
        self.origin6.setText(_translate("Form", "TextLabel"))
        self.fixratio6.setText(_translate("Form", "TextLabel"))
        self.fixfraction6.setText(_translate("Form", "TextLabel"))
        self.kelly6.setText(_translate("Form", "TextLabel"))
        self.optimal6.setText(_translate("Form", "TextLabel"))
        self.william6.setText(_translate("Form", "TextLabel"))
        self.label_7.setText(_translate("Form", "交易成本"))
        self.origin7.setText(_translate("Form", "TextLabel"))
        self.fixratio7.setText(_translate("Form", "TextLabel"))
        self.fixfraction7.setText(_translate("Form", "TextLabel"))
        self.kelly7.setText(_translate("Form", "TextLabel"))
        self.optimal7.setText(_translate("Form", "TextLabel"))
        self.william7.setText(_translate("Form", "TextLabel"))
