# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'useRF.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(829, 669)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_10.addWidget(self.widget)
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(14, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_8.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.choseDataBtn = QtWidgets.QToolButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.choseDataBtn.setFont(font)
        self.choseDataBtn.setObjectName("choseDataBtn")
        self.horizontalLayout_8.addWidget(self.choseDataBtn)
        spacerItem2 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem3 = QtWidgets.QSpacerItem(388, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        spacerItem4 = QtWidgets.QSpacerItem(388, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.startTrainBtn = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.startTrainBtn.setFont(font)
        self.startTrainBtn.setObjectName("startTrainBtn")
        self.horizontalLayout_9.addWidget(self.startTrainBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.profitCol = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.profitCol.setFont(font)
        self.profitCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.profitCol.setObjectName("profitCol")
        self.verticalLayout_4.addWidget(self.profitCol)
        self.winrateCol = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.winrateCol.setFont(font)
        self.winrateCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.winrateCol.setObjectName("winrateCol")
        self.verticalLayout_4.addWidget(self.winrateCol)
        self.winLossCol = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.winLossCol.setFont(font)
        self.winLossCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.winLossCol.setObjectName("winLossCol")
        self.verticalLayout_4.addWidget(self.winLossCol)
        self.profitFactorCol = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.profitFactorCol.setFont(font)
        self.profitFactorCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.profitFactorCol.setObjectName("profitFactorCol")
        self.verticalLayout_4.addWidget(self.profitFactorCol)
        self.mddCol = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.mddCol.setFont(font)
        self.mddCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mddCol.setObjectName("mddCol")
        self.verticalLayout_4.addWidget(self.mddCol)
        self.sharpeCol = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.sharpeCol.setFont(font)
        self.sharpeCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sharpeCol.setObjectName("sharpeCol")
        self.verticalLayout_4.addWidget(self.sharpeCol)
        self.costCol = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.costCol.setFont(font)
        self.costCol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.costCol.setObjectName("costCol")
        self.verticalLayout_4.addWidget(self.costCol)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.profitOut = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Dubai Light")
        font.setPointSize(18)
        self.profitOut.setFont(font)
        self.profitOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.profitOut.setObjectName("profitOut")
        self.verticalLayout.addWidget(self.profitOut)
        self.winRateOut = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Dubai Light")
        font.setPointSize(18)
        self.winRateOut.setFont(font)
        self.winRateOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.winRateOut.setObjectName("winRateOut")
        self.verticalLayout.addWidget(self.winRateOut)
        self.winLossOut = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Dubai Light")
        font.setPointSize(18)
        self.winLossOut.setFont(font)
        self.winLossOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.winLossOut.setObjectName("winLossOut")
        self.verticalLayout.addWidget(self.winLossOut)
        self.profitFactorOut = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Dubai Light")
        font.setPointSize(18)
        self.profitFactorOut.setFont(font)
        self.profitFactorOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.profitFactorOut.setObjectName("profitFactorOut")
        self.verticalLayout.addWidget(self.profitFactorOut)
        self.mddOut = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Dubai Light")
        font.setPointSize(18)
        self.mddOut.setFont(font)
        self.mddOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mddOut.setObjectName("mddOut")
        self.verticalLayout.addWidget(self.mddOut)
        self.tradeCuntOut = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Dubai Light")
        font.setPointSize(18)
        self.tradeCuntOut.setFont(font)
        self.tradeCuntOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tradeCuntOut.setObjectName("tradeCuntOut")
        self.verticalLayout.addWidget(self.tradeCuntOut)
        self.costOut = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Dubai Light")
        font.setPointSize(18)
        self.costOut.setFont(font)
        self.costOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.costOut.setObjectName("costOut")
        self.verticalLayout.addWidget(self.costOut)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.widget_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.dataPath = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.dataPath.setFont(font)
        self.dataPath.setText("")
        self.dataPath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dataPath.setObjectName("dataPath")
        self.verticalLayout_3.addWidget(self.dataPath)
        self.horizontalLayout_10.addWidget(self.groupBox)
        self.widget_2 = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_10.addWidget(self.widget_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "隨機森林"))
        self.label_14.setText(_translate("Form", "選擇商品資料:"))
        self.choseDataBtn.setText(_translate("Form", "..."))
        self.startTrainBtn.setText(_translate("Form", "開始預測"))
        self.label_4.setText(_translate("Form", "績效"))
        self.profitCol.setText(_translate("Form", "淨利:"))
        self.winrateCol.setText(_translate("Form", "勝率:"))
        self.winLossCol.setText(_translate("Form", "賺賠比:"))
        self.profitFactorCol.setText(_translate("Form", "獲利因子:"))
        self.mddCol.setText(_translate("Form", "最大策略虧損:"))
        self.sharpeCol.setText(_translate("Form", "總交易次數:"))
        self.costCol.setText(_translate("Form", "交易成本:"))
        self.profitOut.setText(_translate("Form", "─"))
        self.winRateOut.setText(_translate("Form", "─"))
        self.winLossOut.setText(_translate("Form", "─"))
        self.profitFactorOut.setText(_translate("Form", "─"))
        self.mddOut.setText(_translate("Form", "─"))
        self.tradeCuntOut.setText(_translate("Form", "─"))
        self.costOut.setText(_translate("Form", "─"))
